# Numpy

In [11]:
import numpy

In [12]:
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [13]:
import numpy as np

In [14]:
full = np.full((4,2),2.3)
print(full)

[[2.3 2.3]
 [2.3 2.3]
 [2.3 2.3]
 [2.3 2.3]]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
inserted = np.insert(arr,2,20)
print(arr)
print(inserted)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2 20  3  4  5  6  7  8  9 10 11 12]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
deleted = np.delete(arr,2)
print(arr)
print(deleted)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  4  5  6  7  8  9 10]


In [17]:
arr = np.array([1, 2, 3, 4, 5])
print(type(arr))

<class 'numpy.ndarray'>


In [18]:
arrInteger = np.array(['a','b','c','d'])
arrString = np.array(["maryam", "ali", "arezo", "amir"])
arrFloat = np.array([1.2, 2.0, 3.1, 5.21])
print(arrInteger.dtype)
print(arrString.dtype)
print(arrFloat.dtype)

<U1
<U6
float64


In [19]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(arr)
print(arr.dtype)
print(newarr)
print(newarr.dtype)

[1.1 2.1 3.1]
float64
[1 2 3]
int32


In [20]:
arr = np.array([1, 2, 3, 4])
print(arr[0] + arr[2] * arr[3] / arr[1])

7.0


In [21]:
arr = np.array([1, 2, 3, 4])
print(arr[-1])
print(arr[3])

4
4


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])
print(arr[0:5])
print(arr[4:])
print(arr[:3])

[2 4]
[1 2 3 4 5]
[5 6 7]
[1 2 3]


In [23]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [24]:
arr = np.array([1, 2, 3])
for x in arr:
    print(x)

1
2
3


In [25]:
arr = np.array([1, 2, 3])
for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [26]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
print(newarr[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[5 6]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int32),)


In [29]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
y = np.searchsorted(arr, 7, side='left')
print(x)
print(y)


2
1


In [30]:
num = np.array([3, 2, 0, 1])
string = np.array(['banana', 'cherry', 'apple'])
boolean = np.array([True, False, True])
print(np.sort(num))
print(np.sort(string))
print(np.sort(boolean))

[0 1 2 3]
['apple' 'banana' 'cherry']
[False  True  True]


In [31]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
filteredarr = arr[x]
print(filteredarr)

[41 43]


In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [33]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [34]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [35]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr1 = arr.reshape(4, 3)
newarr2 = arr.reshape(2, 3, 2)
print(newarr1)
print(newarr2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [36]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
newarr = np.stack((arr1, arr2), axis=0)
print(arr)
print(newarr)

[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [37]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [38]:
from numpy import random

In [39]:
x = random.rand()
print(x)

0.001972965721156794


In [40]:
x = random.randint(100, size=(3, 5))
print(x)

[[29 39 56 71 76]
 [56 95  2 98 69]
 [17 49 65 99 57]]


In [41]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[7 7 5 7 5]
 [7 7 7 5 5]
 [5 5 5 3 3]]
